#!/bin/bash

have_python3=`type -p python3`
if [ "${have_python3}" ]
then
  PYTHON="python3"
else
  have_python=`type -p python`
  if [ "${have_python}" ]
  then
    PYTHON="python"
  else
    echo "Python not found. Exiting."
    exit 1
  fi
fi

${PYTHON} -m pip install --upgrade build

${PYTHON} -m build

exit 0
arch=
centos=
debian=
fedora=
rpi=
mach=`uname -m`
if [ -f /etc/os-release ]
then
  . /etc/os-release
  [ "${ID}" == "debian" ] || [ "${ID_LIKE}" == "debian" ] && debian=1
  [ "${ID}" == "arch" ] || [ "${ID_LIKE}" == "arch" ] && arch=1
  [ "${ID}" == "centos" ] && centos=1
  [ "${ID}" == "fedora" ] && fedora=1
  [ "${ID}" == "raspbian" ] && rpi=1
else
  if [ -f /etc/arch-release ]
  then
    arch=1
  else
    case "${mach}" in
      arm*)
        debian=1
        rpi=1
        ;;
      x86*)
        have_apt=`type -p apt`
        if [ "${have_apt}" ]
        then
          debian=1
        else
          if [ -f /etc/fedora-release ]
          then
            fedora=1
          else
            if [ -f /etc/centos-release ]
            then
              centos=1
            else
              have_dnf=`type -p dnf`
              have_yum=`type -p yum`
              if [ "${have_dnf}" ] || [ "${have_yum}" ]
              then
                # Use Fedora for all other rpm based systems
                fedora=1
              else
                echo "Unknown operating system distribution"
              fi
            fi
          fi
        fi
        ;;
      *)
        echo "Unknown machine architecture"
        ;;
    esac
  fi
fi

if [ "${rpi}" ]
then
  platform="rpi"
else
  if [ "${debian}" ]
  then
    platform="debian"
  else
    if [ "${arch}" ]
    then
      platform="arch"
    else
      if [ "${centos}" ]
      then
        platform="centos"
      else
        if [ "${fedora}" ]
        then
          platform="fedora"
        else
          platform="unknown"
        fi
      fi
    fi
  fi
fi

# cd dist
# wheel=`echo *.whl`
# name=`echo $wheel | awk -F '-' ' { print $1 } '`
# version=`echo $wheel | awk -F '-' ' { print $2 } '`
# arch=`echo $wheel | awk -F '-' ' { print $5 } '`
# echo "Moving dist/$wheel to dist/${name}-${version}-${platform}-${arch}"
# mv $wheel ${name}-${version}-${platform}-${arch}
