name: Build

# To publish when a (published) GitHub Release is created, use the following:
on:
  workflow_dispatch:
  release:
    types:
      - published
# Alternatively, build on every branch push, tag push, and pull request change:
# on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          # On a Linux Intel runner with qemu installed
          # Build native archs ('auto'), and some emulated ones
          # CIBW_ARCHS_LINUX: auto aarch64 ppc64le s390x
          # CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_LINUX: auto
          # Disable building PyPy wheels on all platforms
          CIBW_SKIP: pp*
          # On a Linux Intel runner install X11 dev dependencies
          CIBW_BEFORE_ALL_LINUX: yum install -y libX11-devel libXext-devel libXres-devel || apt-get install -y libx11-dev libxext-dev libxres-dev || apk add --upgrade libx11-dev libxext-dev libxres-dev 
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
